In [45]:
#imporing the required library
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

In [ ]:
#comparative analysis of diabetic patients

In [31]:
#uploding the CSV dataset and reading
dataset=pd.read_csv("/content/KNN_Dataset.csv")

In [33]:
#length of dataset
len(dataset)

768

In [35]:
#getting first 5 rows using head
dataset.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [8]:
#replace zeros
zero_not_accepted=['Glucose','BloodPressure','SkinThickness','BMI','Insulin']

In [36]:
#replace by mean value
for column in zero_not_accepted:
 dataset[column]=dataset[column].replace(0,np.NaN)
 mean=int(dataset[column].mean(skipna=True))
 dataset[column]=dataset[column].replace(np.NaN,mean)

In [37]:
#row, column segregation
X=dataset.iloc[:,0:8]
y=dataset.iloc[:,8]
X_train,X_test,y_train,y_test=train_test_split(X,y, random_state=0,test_size=0.2)

In [39]:
#converting to standard form n storing
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.transform(X_test)

In [22]:
#we can change it to any type of distance measures
classifier=KNeighborsClassifier(n_neighbors=11,p=2,metric='euclidean')

In [23]:
#applying classifier to the data
classifier.fit(X_train,y_train)
KNeighborsClassifier(algorithm='auto',leaf_size=30, metric='euclidean',metric_params=None,n_jobs=1,n_neighbors=11)

KNeighborsClassifier(metric='euclidean', n_jobs=1, n_neighbors=11)

In [40]:
#predicting using classifiers
y_pred=classifier.predict(X_test)
y_pred

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [43]:
#getting confusion matrix for f1score
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(f1_score(y_test,y_pred))

[[94 13]
 [15 32]]
0.6956521739130436


In [44]:
#getting confusion matrix for accuracy
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(accuracy_score(y_test,y_pred))

[[94 13]
 [15 32]]
0.8181818181818182
